### PR TITLE
adds from Chick3nman's hashcat kernel and Python script

### PR DESCRIPTION
**Pull request by roycewilliams**
Note that the whitespace changes in sha256.md are due to converting from DOS to Unix line separators to match the other files. And actually credit to @hops for the kernel work as well. :smile:

### CODE REVIEW

**Comment by roycewilliams** [comment]
And actually credit to @hops for the kernel work as well. :smile:

**Comment by spaze** [comment]
Hey, awesome work, thanks! I took the liberty and modified your pull request. I've converted the newlines in my repo (thanks for spotting those CRLFs) so this PR didn't need to change them.

**Comment by roycewilliams** [comment]
All credit to @Chick3nman and @hops for the work - I just supplied some horsepower. And I totally trust your judgment on modifying PRs as needed. :D

**Comment by spaze** [comment]
FYI, one more change, the backslash is not part of the string, just to escape the backtick (it wasn't a magic hash otherwise):
```
- CGq'v]\`1
+ CGq'v]`1
```

**Comment by roycewilliams** [comment]
Yikes - good catch, sorry I missed that!

**Pull request merged**
